# -*- coding: utf-8 -*-
"""Assignment 4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/195902qZYlqE2g_pnDadxo3S363ZHpdju

Name: Marim Ibrahim

AUS ID: 00104172

Question 1:
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

df = pd.read_excel("dubizzle_cars_dataset.xlsx", "Data")
absolute_frequencies = df['warranty'].value_counts()
df2 = pd.DataFrame({'Car Warranty': absolute_frequencies}, index = ['Yes', 'No'] )
df2.plot.pie(y='Car Warranty', figsize=(5,5), autopct='%1.1f%%')

sns.set(style='darkgrid')
plt.figure(figsize=(5,5))
sns.countplot(x='fuel_type', data=df, hue=df['fuel_type'])

df3 = df["price"]
a = df3.to_numpy()
print("The mean of car prices is: ", a.mean())

print(np)

n1 = np.min(a)
n2 = np.percentile(a, 25)
n3=  np.percentile(a, 50)
n4 = np.percentile(a, 75)
n5= np.max(a)
print('Five number summary: ',n1,' ',n2,' ', n3, ' ', n4, ' ',n5)

#mydata = np.random.normal(a.mean(), np.std(a), np.count_nonzero(a))
sns.set(style="darkgrid")
plt.figure(figsize=(10,8))
ax = sns.histplot(data = df3)
ax.set_xlabel("Car Price")
ax.set_ylabel("Frequency")
ax.set_title("Histogram of data")
plt.show()
print("The data is symmetric and there are no outliers")

ax = sns.boxplot(data=df3)

toyota_data = data = df.loc[df.brand == "Toyota"]
sns.set(style='darkgrid')
plt.figure(figsize=(5,5))
sns.countplot(x='seller_type', data=df, hue=df['seller_type'])
print("The seating capacity of most sold Nissan cars is 5")

nissan_data = data = df.loc[df.brand == "Nissan"]
absolute_frequencies = df['seating_capacity'].value_counts()
df2 = pd.DataFrame({'Seating Capacity': absolute_frequencies})
df2.plot.pie(y='Seating Capacity', figsize=(5,5), autopct='%1.1f%%')

data_numerical_columns = data.select_dtypes(include=["number"])
sns.heatmap(data_numerical_columns.corr(),annot=True)
plt.show()

print("Two positive correltaions are seating capacity and number of cylinders and number of cylinders and price")
print("Two negative correltaions are vehicle age years and year and kilometers and year")