# -*- coding: utf-8 -*-
"""September 9

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ztVynbCNHM-KwOSzbEOEYQjVx7th16vj
"""

x = 1.5
y = 3
z = "Hello world"

print("Type of x: ", type(x))
print("Type of y: ", type(y))
print("Type of z: ", type(z))

z = "100"
a = int(z)
print(a)
print("Type of a: ", type(a))

b = 12.6
print(float(int((b))))

name = input("Enter your name: ")
print(name)
age = int(input("Enter your age: "))
print(age)

x = input("Enter a value: ")
y = input("Enter a value: ")
print(x + y)

list1 = [8, 5, 5, 10.45, 6, 24, "Monday"]
print(list1)
print(list1[4])
print(list1[2:6])

roman_numerals = {"I": 1, "II": 2, "III": 3, "V": 5, "X": 10}
print(roman_numerals['X'])

grade_book = {
    "Ali": [82, 54, 67, 84],
    "Huda": [73, 6, 56, 90]
}
print(grade_book["Ali"])
print(grade_book["Ali"][2])
grade_book.update({"Huda" : [100, 90, 70, 34]})
print(grade_book["Huda"])

