# -*- coding: utf-8 -*-
"""Practice Exercises Part 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cqVWgsXCwCFDt2K7h1SWuEEsc9u6imZc
"""

import numpy as np
array = np.array([
    [72, 1060, 18279, 1506],
    [547, 745, 2865, 802],
    [390, 1880, 4160, 5080],
    [476, 895, 987, 450],
    [1580, 722, 7357, 1256],
    [789, 1463, 1098, 8647]])
print(array)

array = np.array([
    [72, 1060, 18279, 1506],
    [547, 745, 2865, 802],
    [390, 1880, 4160, 5080],
    [476, 895, 987, 450],
    [1580, 722, 7357, 1256],
    [789, 1463, 1098, 8647]])
print(np.sort(array))

array = np.array([
    [72, 1060, 18279, 1506],
    [547, 745, 2865, 802],
    [390, 1880, 4160, 5080],
    [476, 895, 987, 450],
    [1580, 722, 7357, 1256],
    [789, 1463, 1098, 8647]])
print(array.sum(axis=1))
print(array.sum(axis=0))
print(array.sum())

array = np.array([
    [72, 1060, 18279, 1506],
    [547, 745, 2865, 802],
    [390, 1880, 4160, 5080],
    [476, 895, 987, 450],
    [1580, 722, 7357, 1256],
    [789, 1463, 1098, 8647]])
print(array[0,0])
print(array[2,2])
print(array[5,1])

array = np.array([
    [72, 1060, 18279, 1506],
    [547, 745, 2865, 802],
    [390, 1880, 4160, 5080],
    [476, 895, 987, 450],
    [1580, 722, 7357, 1256],
    [789, 1463, 1098, 8647]])
print(array[2])

array = np.array([
    [72, 1060, 18279, 1506],
    [547, 745, 2865, 802],
    [390, 1880, 4160, 5080],
    [476, 895, 987, 450],
    [1580, 722, 7357, 1256],
    [789, 1463, 1098, 8647]])
print(array[2])
print(array[3])
print(array[4])

array = np.array([
    [72, 1060, 18279, 1506],
    [547, 745, 2865, 802],
    [390, 1880, 4160, 5080],
    [476, 895, 987, 450],
    [1580, 722, 7357, 1256],
    [789, 1463, 1098, 8647]])
print(array[:,1])

array = np.array([
    [72, 1060, 18279, 1506],
    [547, 745, 2865, 802],
    [390, 1880, 4160, 5080],
    [476, 895, 987, 450],
    [1580, 722, 7357, 1256],
    [789, 1463, 1098, 8647]])
print(array[:,1:3])

array = np.array([
    [72, 1060, 18279, 1506],
    [547, 745, 2865, 802],
    [390, 1880, 4160, 5080],
    [476, 895, 987, 450],
    [1580, 722, 7357, 1256],
    [789, 1463, 1098, 8647]])
print(array[2:4,0:3])

array = np.array([
    [72, 1060, 18279, 1506],
    [547, 745, 2865, 802],
    [390, 1880, 4160, 5080],
    [476, 895, 987, 450],
    [1580, 722, 7357, 1256],
    [789, 1463, 1098, 8647]])
print(array[[2,4],0:3])

array = np.array([
    [72, 1060, 18279, 1506],
    [547, 745, 2865, 802],
    [390, 1880, 4160, 5080],
    [476, 895, 987, 450],
    [1580, 722, 7357, 1256],
    [789, 1463, 1098, 8647]])
print(array[2:5:2,0:3:2])

import pandas as pd
my_dataframe = pd.DataFrame(array)

my_dataframe = pd.DataFrame(array, columns=["Grapefruit", "Lemons", "Oranges", "Mango"])
print(my_dataframe)

print(my_dataframe["Lemons"])

print(my_dataframe.iloc[2])
print(my_dataframe.iloc[3])
print(my_dataframe.iloc[4])
print(my_dataframe.iloc[:,1])
print(my_dataframe.iloc[:,1:3])
print(my_dataframe.iloc[2:4,0:3])
print(my_dataframe.iloc[[2,4],0:3])
print(my_dataframe.iloc[2:5:2,0:3:2])

print(my_dataframe[my_dataframe > 1000])
print(my_dataframe[(my_dataframe > 500) & (my_dataframe < 1500)])