# -*- coding: utf-8 -*-
"""Assignment 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Vh542qVUoM32k8ZODWxlToMvb0edPky

Name: Marim Ibrahim

AUS ID: 00104172

Question 1:
"""

import numpy as np
Ages = np.array([18, 22, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 23, 28, 33, 38, 43, 48, 53, 58, 63, 68,
73, 78, 26, 31, 36, 41])
print("The number of employees in the company is: ", Ages.size)
print("The age of the youngest employee is: ", Ages.min())
print("The age of the oldest employee is: ", Ages.max())
print("The average age of the employees is: ", Ages.sum()/Ages.size)
print("The standard deviation is: ", np.std(Ages))
Ages_sorted = np.sort(Ages)
print("The ages sorted from youngest to oldest is: ", Ages_sorted)
Ages_reshaped = Ages_sorted.reshape(3,10)
print("The reshaped and sorted array is: \n", Ages_reshaped)
Ages_transposed = np.transpose(Ages_reshaped)
print("The transposed array is: \n", Ages_transposed)

"""Question 2:"""

import pandas as pd
data_Dictionary = {
    "Country" : ["United States", "Canada", "United Kingdom", "Germany", "Australia", "France", "Japan", "China", "India", "Brazil"],
    "Population (in millions)" : [331, 38, 67, 83, 26, 65, 126, 1440, 1393, 214],
    "GPD (trillions)" : [21.43, 1.64, 2.83, 3.85, 1.33, 2.72, 5.08, 17.73, 3.05, 2.05]
}
data_Dataframe = pd.DataFrame(data_Dictionary)
print(data_Dataframe)
print("\n")
print(data_Dataframe.describe())
print("\n")
data_Dataframe.columns=["Country", "Population", "GPD"]
data = data_Dataframe.loc[data_Dataframe.Population < 100]
print("The countries with a population less than 100 million are: \n", data.head())
print("\n")
data2 = data_Dataframe.loc[data_Dataframe.GPD > 5]
print("The countries with a GPD more than 5 trillion are: \n", data2.head())

"""Question 3:"""

import pandas as pd
df = pd.read_excel("dubizzle_cars_dataset.xlsx", "Data")
print(df.head())
print("\n")
print(df.describe())
print("\n")
print("Number of attributes in the dataframe: ", df.shape[1])
print("Number of observations (cars) in the dataframe: ", df.shape[0])
print("\n")
data = df.loc[df.brand == "Toyota"]
print("Number of Toyota cars is: ", data.shape[0])
print("\n")
price = data.iloc[:,0]
print("The price of the cheapest Toyota car is: ", price.min())
print("\n")
kilometers = data.iloc[:,4]
car_kilometers = data.loc[data.kilometers == kilometers.max()]
print("The Toyota cars with the highest kilometers are: \n", car_kilometers.head())
print("\n")
year = data.iloc[:, 5]
car_age = data.loc[data.year == year.min()]
print("The oldest Toyota cars are: \n", car_age.head())